$2a)\;\;f(w_1,\;w_2)\;=\;0.1w_1^2\;+\;2w_2^2$

$Bắt\;đầu\;với\;epoch\;=\;1$

$•\;STEP1:\;Tìm\;giá\;trị\;dw_1\;và\;dw_2\;giá\;trị\;đạo\;hàm\;của\;hàm\;theo\;w_1\;và\;w_2\;(partial\;derivative)\;tại\;điểm\;khởi\;tạo\;[w_1,\;w_2]$

$•\;STEP2:\;Tìm\;giá\;trị\;v_1\;và\;v_2\;dựa\;vào\;dw_1\;và\;dw_2\;tìm\;được\;ở\;step\;1\;(công\;thức\;:\;V_t\;=\;βV_{t−1}\;+\;(1\;−\;β)dW_t\;).$

$•\;STEP3:\;Dùng\;công\;thức\;(W_t\;=\;W_t\;−\;α\;∗\;V_t)\;Gradient\;Descent\;+\;Momentum\;để\;cập\;nhật\;w_1\;và\;w_2.\;Hoàn\;thành\;epoch\;=\;1$

$•\;STEP4:\;epoch\;=\;2\;ta\;thực\;hiện\;tương\;tự\;với\;STEP1,\;STEP2\;và\;STEP3\;như\;trên\;với\;w_1\;và\;w_2\;đã\;được\;cập\;nhật\;từ\;epoch\;=\;1$


In [28]:
import numpy as np

In [29]:
def df_w(W):

    w1, w2 = W
    
    # Tính gradient
    dw1 = 0.2 * w1  # Đạo hàm riêng theo w1
    dw2 = 4 * w2    # Đạo hàm riêng theo w2
    
    # Tạo vector gradient
    dW = np.array([dw1, dw2])

    return dW

In [30]:
def sgd_momentum(W, dW, lr, V, beta):
    # Cập nhật momentum
    V = beta * V + (1 - beta) * dW  # Cập nhật v1 và v2

    # Cập nhật tham số
    W = W - lr * V  # Cập nhật w1 và w2

    return W, V

In [31]:
def train_p1(optimizer, lr, epochs):

    # Khởi tạo giá trị ban đầu
    W = np.array([-5, -2], dtype=np.float32)  # [w1, w2]
    V = np.array([0, 0], dtype=np.float32)   # [v1, v2] (momentum ban đầu)
    results = [W]                     # Lưu lại W ban đầu

    # Vòng lặp theo số epoch
    for epoch in range(epochs):
        dW = df_w(W) 

        # Cập nhật W và V bằng thuật toán optimizer
        W, V = optimizer(W, dW, lr, V, beta=0.5)

        # Lưu giá trị [w1, w2] sau mỗi epoch
        results.append(W)

    return results

In [32]:
train_p1(sgd_momentum, lr=0.6, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.7,  0.4]),
 array([-4.268,  1.12 ]),
 array([-3.79592,  0.136  ]),
 array([-3.3321248, -0.5192   ]),
 array([-2.90029971, -0.22376   ]),
 array([-2.51036919,  0.192472  ]),
 array([-2.16478177,  0.1696216 ]),
 array([-1.86210116, -0.04534952]),
 array([-1.59903478, -0.09841566]),
 array([-1.37155951, -0.00684994]),
 array([-1.1755283 ,  0.04715285]),
 array([-1.006981  ,  0.01757082]),
 array([-0.86228849, -0.01830518]),
 array([-0.73820492, -0.01427696]),
 array([-0.63187084,  0.0048695 ]),
 array([-0.54079155,  0.00859933]),
 array([-4.62804416e-01,  1.45050014e-04]),
 array([-0.39604258, -0.00425615]),
 array([-0.33889911, -0.00134937]),
 array([-0.28999343,  0.00172326]),
 array([-0.24814098,  0.00119166]),
 array([-0.2123263 , -0.00050413]),
 array([-0.18167938, -0.00074707]),
 array([-1.55455157e-01,  2.79448010e-05]),
 array([-0.13301574,  0.00038192]),
 array([-1.13815082e-01,  1.00603444e-04]),
 array([-0.09738585, -0.00016078]),
 