$3a)\;\;f(w_1,\;w_2)\;=\;0.1w_1^2\;+\;2w_2^2$

$•\;Bắt\;đầu\;với\;epoch\;=\;1$

$•\;STEP1:\;Tìm\;giá\;trị\;dw_1\;và\;dw_2\;giá\;trị\;đạo\;hàm\;của\;hàm\;(S_t\;=\;γS_{t−1}\;+\;(1\;−\;γ)dW_t^2)$
$theo\;w_1\;và\;w_2\;(partial\;derivative)\;tại\;điểm\;khởi\;tạo\;[w_1,\;w_2]$

$•\;STEP2:\;Tìm\;giá\;trị\;s_1\;và\;s_2\;dựa\;vào\;dw_1\;và\;dw_2\;vừa\;tìm\;được\;ở\;STEP1.$

$•\;STEP3:\;Dùng\;công\;thức\;(W_t\;=\;W_t\;−\;α\;∗\; \frac{dW}{\sqrt{St\;+\;ε}})\;để\;cập\;nhật\;w_1\;và\;w_2.\;Hoàn\;thành\;epoch\;=\;1$

$•\;STEP4:\;epoch\;=\;2\;ta\;thực\;hiện\;tương\;tự\;với\;STEP1,\;STEP2\;và\;STEP3\;như\;trên\;với\;w_1\;và\;w_2\;đã\;được\;cập\;nhật\;từ\;epoch\;=\;1$

In [53]:
import numpy as np

In [54]:
def df_w(W):

    w1, w2 = W
    
    # Tính gradient
    dw1 = 0.2 * w1  # Đạo hàm riêng theo w1
    dw2 = 4 * w2    # Đạo hàm riêng theo w2
    
    # Tạo vector gradient
    dW = np.array([dw1, dw2])

    return dW

In [55]:
def RMSProp(W, dW, lr, S, gamma):
    epsilon = 1e-6
    S = gamma * S + (1 - gamma) * dW**2
    W = W - lr * dW / np.sqrt(S + epsilon)
    return W, S


In [56]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    
    
    for epoch in range(epochs):
        # Tính gradient
        dW = df_w(W) 

        # Cập nhật W và S bằng thuật toán optimizer
        W, S = optimizer(W, dW, S, lr, gamma=0.9)

        # Lưu giá trị [w1, w2] sau mỗi epoch
        results.append(W)

    return results

In [58]:
train_p1(RMSProp, lr=0.3, epochs=30)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9536\1084144679.py:4: RuntimeWarning: overflow encountered in multiply
  W = W - lr * dW / np.sqrt(S + epsilon)
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9536\1084144679.py:4: RuntimeWarning: invalid value encountered in divide
  W = W - lr * dW / np.sqrt(S + epsilon)


[array([-5., -2.], dtype=float32),
 array([-5., -2.]),
 array([-4.39172457, 18.66107296]),
 array([-3.84014491, -2.42621033]),
 array([  -3.37530483, 1735.63919542]),
 array([  -2.97996325, 1705.00180272]),
 array([-2.63969880e+00, -1.52401874e+07]),
 array([-2.34416344e+00, -5.31643139e+05]),
 array([-2.08571732e+00,  1.17516974e+15]),
 array([-1.85852463e+00,  1.17373966e+15]),
 array([-1.65800040e+00, -6.98748971e+30]),
 array([-1.48045826e+00, -1.69959975e+28]),
 array([-1.32287699e+00,  2.47037194e+62]),
 array([-1.18274084e+00,  2.47035732e+62]),
 array([-1.05792706e+000, -3.08776808e+125]),
 array([-9.46624741e-001, -3.65362809e+120]),
 array([-0.84727492,         inf]),
 array([-0.75852545,         nan]),
 array([-0.67919634,         nan]),
 array([-0.60825268,         nan]),
 array([-0.54478302,         nan]),
 array([-0.48798204,         nan]),
 array([-0.43713618,         nan]),
 array([-0.39161187,         nan]),
 array([-0.35084552,         nan]),
 array([-0.31433509,     