$4a)\;\;f(w_1,\;w_2)\;=\;0.1w_1^2\;+\;2w_2^2$

$•\;Bắt\;đầu\;với\;epoch\;=\;1$

$•\;STEP1:\;Tìm\;giá\;trị\;dw_1\;và\;dw_2\;giá\;trị\;đạo\;hàm\;của\;hàm\;(1)\;theo\;w_1\;và\;w_2\;(partial\;derivative)\;tại\;điểm\;khởi\;tạo\;[w_1,\;w_2]$

$•\;STEP2:\;Tìm\;giá\;trị\;v_1\;và\;v_2\;dựa\;vào\;dw1\;và\;dw2\;vừa\;tìm\;được\;ở\;step\;1\;(V_t\;=\;β_1V_{t−1}\;+\;(1\;−\;β_1)dW_t).$

$•\;STEP3:\;Tìm\;giá\;trị\;s_1\;và\;s_2\;dựa\;vào\;dw1\;và\;dw2\;vừa\;tìm\;được\;ở\;step\;1\;(S_t\;=\;β_2S_{t−1}\;+\;(1\;−\;β_2)dW_t^2).$

$•\;STEP4:\;Thực\;hiện\;bias-correction\;cho\;V\;và\;S\;để\;thu\;được\;V_coor\;và\;S_coor.\;Sau\;khiáp\;dụng\;bias\;correction\;$

$(V_{coor}\;=\;\frac{V_t}{1-β_1^t})\;và\;(S_{coor}\;=\;\frac{S_t}{1-β_2^t})\;ta\;sẽ\;thu\;được\;v_{coor1},\;v_{coor2},\;s_{coor1}\;và\;s_{coor2}$

$•\;STEP5:\;Dùng\;công\;thức\;(W_t\;=\;W_t\;−\;α\;∗\;\;\frac{dW}{\sqrt{St\;}+\;ε})\;để\;cập\;nhật\;w_1\;và\;w_2.\;Hoàn\;thành\;epoch\;=\;1$

$•\;STEP6:\;epoch\;=\;2\;ta\;thực\;hiện\;tương\;tự\;với\;STEP1\;-\;STEP5\;như\;trên\;với\;w1\;và\;w_2\;đã\;được\;cập\;nhật\;từ\;epoch\;=\;1$

In [1]:
import numpy as np

In [2]:
def df_w(W):

    w1, w2 = W
    
    # Tính gradient
    dw1 = 0.2 * w1  # Đạo hàm riêng theo w1
    dw2 = 4 * w2    # Đạo hàm riêng theo w2
    
    # Tạo vector gradient
    dW = np.array([dw1, dw2])

    return dW

In [3]:
import numpy as np

def Adam(W, dW, lr, V, S, beta1, beta2, t):
    
    epsilon = 1e-6  # Giá trị nhỏ để tránh chia cho 0

    # Cập nhật V (momentum vector)
    V = beta1 * V + (1 - beta1) * dW

    # Cập nhật S (RMSProp vector)
    S = beta2 * S + (1 - beta2) * (dW ** 2)

    # Bias correction cho V và S
    V_corr = V / (1 - beta1 ** t)
    S_corr = S / (1 - beta2 ** t)

    # Cập nhật W theo công thức Adam
    W = W - lr * V_corr / (np.sqrt(S_corr) + epsilon)

    return W, V, S

In [4]:
import numpy as np

def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimizer : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # Khởi tạo các tham số ban đầu
    W = np.array([-5, -2], dtype=np.float32)  # Giá trị khởi tạo [w1, w2]
    V = np.array([0, 0], dtype=np.float32)    # Giá trị khởi tạo [v1, v2]
    S = np.array([0, 0], dtype=np.float32)    # Giá trị khởi tạo [s1, s2]
    results = [W.copy()]                      # Lưu kết quả sau mỗi epoch (bắt đầu bằng giá trị khởi tạo)

    for t in range(1, epochs + 1):
        dW = df_w(W)

        # Sử dụng thuật toán optimizer để cập nhật W, V, và S
        W, V, S = optimizer(W, dW, lr, V, S, beta1=0.9, beta2=0.999, t=t)

        # Lưu kết quả [w1, w2] sau mỗi epoch
        results.append(W.copy())

    return results

In [5]:
train_p1(Adam, lr=0.2, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.8000002 , -1.80000002]),
 array([-4.60025478, -1.60082451]),
 array([-4.40094848, -1.40317262]),
 array([-4.20227764, -1.20787822]),
 array([-4.00445033, -1.01592745]),
 array([-3.80768638, -0.82847307]),
 array([-3.61221732, -0.64684159]),
 array([-3.41828623, -0.47252765]),
 array([-3.22614739, -0.30716934]),
 array([-3.03606592, -0.15249855]),
 array([-2.84831706, -0.01026326]),
 array([-2.66318543,  0.11787552]),
 array([-2.480964  ,  0.23046161]),
 array([-2.30195279,  0.3263587 ]),
 array([-2.12645742,  0.40484195]),
 array([-1.95478732,  0.46564961]),
 array([-1.7872537 ,  0.50898799]),
 array([-1.62416726,  0.53549442]),
 array([-1.46583566,  0.54617144]),
 array([-1.31256067,  0.54230812]),
 array([-1.16463526,  0.52540206]),
 array([-1.02234036,  0.4970906 ]),
 array([-0.88594163,  0.4590951 ]),
 array([-0.75568617,  0.41317781]),
 array([-0.63179919,  0.3611089 ]),
 array([-0.51448089,  0.30464048]),
 array([-0.40390346,  0.24548